In [5]:
# 1st Question
#Create a 2D numpy array with 5x5 elements and store it in .npy file and display.
import numpy as np
x = np.random.random((5,5)3
                    
                    
                     
                        )
print("2D Array:")
print(x)
np.save('saved_data',x)

2D Array:
[[0.96911932 0.21230613 0.88481709 0.69864025 0.82437989]
 [0.63006662 0.95076212 0.15657275 0.85302267 0.7061975 ]
 [0.33104752 0.16064553 0.44529747 0.18706782 0.53919934]
 [0.54285558 0.36065964 0.76084764 0.29478502 0.99099415]
 [0.9546539  0.65946318 0.62167686 0.10592927 0.50158178]]


In [9]:
loaded_data = np.load('saved_data.npy')

In [11]:
loaded_data

array([[0.96911932, 0.21230613, 0.88481709, 0.69864025, 0.82437989],
       [0.63006662, 0.95076212, 0.15657275, 0.85302267, 0.7061975 ],
       [0.33104752, 0.16064553, 0.44529747, 0.18706782, 0.53919934],
       [0.54285558, 0.36065964, 0.76084764, 0.29478502, 0.99099415],
       [0.9546539 , 0.65946318, 0.62167686, 0.10592927, 0.50158178]])

In [28]:
# 2ND QUESTION
#Create a .csv file in the name demo and store reg.no, name, section, mark1, mark2, mark3 values of 10 students.
a = np.array("A,B,C,D,E,F,G,H,I,J".split(','))
b= list(np.array(('D2,'*10).split(',')))
mark1 =  np.random.randint(100,size=(10,))
mark2 =  np.random.randint(100,size=(10,))
mark3 =  np.random.randint(100,size=(10,))
b.pop()

''

In [29]:
mark1.shape


(10,)

In [30]:
data = np.array([[a],[b],[mark1],[mark2],[mark3]])
data

array([[['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']],

       [['D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2', 'D2']],

       [['7', '87', '70', '20', '46', '47', '0', '66', '81', '57']],

       [['53', '47', '26', '3', '94', '4', '91', '99', '84', '73']],

       [['83', '27', '9', '61', '73', '12', '41', '70', '86', '37']]],
      dtype='<U11')

In [31]:
data.shape

(5, 1, 10)

In [32]:
data_n = data.reshape(5,10)
data_n.T

array([['A', 'D2', '7', '53', '83'],
       ['B', 'D2', '87', '47', '27'],
       ['C', 'D2', '70', '26', '9'],
       ['D', 'D2', '20', '3', '61'],
       ['E', 'D2', '46', '94', '73'],
       ['F', 'D2', '47', '4', '12'],
       ['G', 'D2', '0', '91', '41'],
       ['H', 'D2', '66', '99', '70'],
       ['I', 'D2', '81', '84', '86'],
       ['J', 'D2', '57', '73', '37']], dtype='<U11')

In [33]:
csv_rows = ["{},{},{},{},{}".format(i, j, k,m,n) for i, j, k, m, n in data_n.T]
csv_text = "\n".join(csv_rows)

with open('sample.csv', 'w') as f:
    f.write(csv_text)

In [34]:
f.close

<function TextIOWrapper.close()>

In [35]:
# 3RD QUESTION
#Load the demo.csv file content into numpy array.
with open('sample.csv','r') as f:
    txt  = f.readlines()
data = np.genfromtxt('sample.csv',delimiter=",",skip_header=True,dtype =str)
data

array([['B', 'D2', '87', '47', '27'],
       ['C', 'D2', '70', '26', '9'],
       ['D', 'D2', '20', '3', '61'],
       ['E', 'D2', '46', '94', '73'],
       ['F', 'D2', '47', '4', '12'],
       ['G', 'D2', '0', '91', '41'],
       ['H', 'D2', '66', '99', '70'],
       ['I', 'D2', '81', '84', '86'],
       ['J', 'D2', '57', '73', '37']], dtype='<U2')